version: 2
jobs:
  build:
    docker:
      - image: athos/clj-lib-dev

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -A:check:test:coverage -Stree

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run:
          name: test CLJ
          command: clojure -Atest

      - run:
          name: test CLJS
          command: clojure -Atest:test-cljs

      - run:
          name: test coverage
          command: |
            clojure -A:test:coverage
            bash <(curl -s https://codecov.io/bash)
